-- Device-linking relay for cross-device credential transfer.
--
-- The server is a DUMB RELAY: it only ever holds a sealed-box ciphertext that
-- was encrypted to the NEW device's ephemeral public key. The server has no
-- private key and cannot decrypt it. This lets a fully set-up "trusted" device
-- (A) hand its locally-stored credentials to a fresh device (B) without the
-- server ever seeing plaintext.
--
-- Flow:
--   1. B (fresh, unauthenticated) generates an ephemeral keypair + random
--      link_id, displays a QR { link_id, pub }.
--   2. A (authenticated) scans the QR, seals its credential bundle to `pub`,
--      and POSTs { link_id, recipient_pub, ciphertext } — this row.
--   3. B polls GET ?link_id=... ; on first hit the row is consumed (deleted).
--
-- Security:
--   - link_id is high-entropy and single-use (deleted on first successful read).
--   - ciphertext is useless without B's ephemeral private key (never leaves B).
--   - rows self-expire in a few minutes.
--   - all access goes through /api/device-link (service_role); no anon policies.
create table if not exists device_link (
  link_id        text primary key,          -- random, generated by device B
  recipient_pub  text not null,             -- B's ephemeral public key (base64)
  ciphertext     text not null,             -- sealed-box from A (base64)
  created_at     timestamptz not null default now(),
  expires_at     timestamptz not null default (now() + interval '3 minutes')
);

create index if not exists idx_device_link_expires on device_link(expires_at);

alter table device_link enable row level security;
-- No anon/authenticated policies: only the service_role API may touch this table.
