-- =============================================================
-- NGワード ログテーブル + 一括登録
-- (action = 'log' : ブロックせずログ記録のみ)
-- Supabase Dashboard の SQL Editor で実行
-- =============================================================

-- 1. NGワードテーブル作成
create table if not exists ng_words (
  id              bigint generated always as identity primary key,
  word            text not null,
  match_type      text not null default 'contains',  -- contains, exact, regex
  action          text not null default 'block',      -- block, warn, log
  category        text default 'general',             -- general, spam, slur, ad, sexual, other
  added_by        bigint references profiles(moodle_id),
  created_at      timestamptz default now()
);
create unique index if not exists idx_ng_words_word on ng_words(lower(word));
alter table ng_words enable row level security;

-- 2. ログテーブル作成
create table if not exists ng_word_logs (
  id              bigint generated always as identity primary key,
  matched_words   text[] not null,
  action_taken    text not null default 'log',    -- log, block
  text_snippet    text,                           -- 先頭100文字
  user_id         bigint references profiles(moodle_id),
  content_type    text,                           -- post, comment, message, dm
  course_id       text,
  created_at      timestamptz default now()
);
create index if not exists idx_ng_word_logs_created on ng_word_logs(created_at desc);
create index if not exists idx_ng_word_logs_user on ng_word_logs(user_id);
alter table ng_word_logs enable row level security;

-- 3. NGワード一括登録
INSERT INTO ng_words (word, match_type, action, category) VALUES

-- ========== 差別・誹謗中傷 (slur) ==========
('死ね', 'contains', 'log', 'slur'),
('殺す', 'contains', 'log', 'slur'),
('殺してやる', 'contains', 'log', 'slur'),
('消えろ', 'contains', 'log', 'slur'),
('自殺しろ', 'contains', 'log', 'slur'),
('キモい', 'contains', 'log', 'slur'),
('キモすぎ', 'contains', 'log', 'slur'),
('きもい', 'contains', 'log', 'slur'),
('ガイジ', 'contains', 'log', 'slur'),
('池沼', 'contains', 'log', 'slur'),
('知障', 'contains', 'log', 'slur'),
('障害者w', 'contains', 'log', 'slur'),
('チョン', 'contains', 'log', 'slur'),
('在日', 'contains', 'log', 'slur'),
('シナ人', 'contains', 'log', 'slur'),
('土人', 'contains', 'log', 'slur'),
('部落', 'contains', 'log', 'slur'),
('穢多', 'contains', 'log', 'slur'),
('非人', 'contains', 'log', 'slur'),
('カタワ', 'contains', 'log', 'slur'),
('めくら', 'contains', 'log', 'slur'),
('つんぼ', 'contains', 'log', 'slur'),
('びっこ', 'contains', 'log', 'slur'),
('気違い', 'contains', 'log', 'slur'),
('キチガイ', 'contains', 'log', 'slur'),
('基地外', 'contains', 'log', 'slur'),
('ガイキチ', 'contains', 'log', 'slur'),
('クズ', 'contains', 'log', 'slur'),
('カス', 'contains', 'log', 'slur'),
('ゴミ人間', 'contains', 'log', 'slur'),
('生きる価値ない', 'contains', 'log', 'slur'),
('生きてる意味ない', 'contains', 'log', 'slur'),
('社会のゴミ', 'contains', 'log', 'slur'),
('人間のクズ', 'contains', 'log', 'slur'),
('ゴミカス', 'contains', 'log', 'slur'),
('クソガキ', 'contains', 'log', 'slur'),
('ブス', 'contains', 'log', 'slur'),
('デブス', 'contains', 'log', 'slur'),
('チビデブ', 'contains', 'log', 'slur'),
('ハゲデブ', 'contains', 'log', 'slur'),
('肌が汚い', 'contains', 'log', 'slur'),
('不細工', 'contains', 'log', 'slur'),
('奇形', 'contains', 'log', 'slur'),
('発達障害w', 'contains', 'log', 'slur'),
('アスペw', 'contains', 'log', 'slur'),
('糖質', 'contains', 'log', 'slur'),
('メンヘラw', 'contains', 'log', 'slur'),
('ナマポ', 'contains', 'log', 'slur'),
('乞食', 'contains', 'log', 'slur'),
('ホームレスw', 'contains', 'log', 'slur'),
('童貞w', 'contains', 'log', 'slur'),
('処女w', 'contains', 'log', 'slur'),
('ヤリマン', 'contains', 'log', 'slur'),
('ヤリチン', 'contains', 'log', 'slur'),
('肉便器', 'contains', 'log', 'slur'),
('売春', 'contains', 'log', 'slur'),
('援交', 'contains', 'log', 'slur'),
('パパ活', 'contains', 'log', 'slur'),
('ママ活', 'contains', 'log', 'slur'),

-- ========== 差別・誹謗中傷 regex ==========
('死ねよ', 'regex', 'log', 'slur'),
('(ころ|コロ)す(ぞ|ぜ)', 'regex', 'log', 'slur'),
('き+も+い+', 'regex', 'log', 'slur'),
('う+ざ+い+', 'regex', 'log', 'slur'),
('ｷﾁｶﾞｲ', 'regex', 'log', 'slur'),
('ガ\s*イ\s*ジ', 'regex', 'log', 'slur'),
('氏\s*ね', 'regex', 'log', 'slur'),
('タヒ\s*ね', 'regex', 'log', 'slur'),
('くたばれ', 'regex', 'log', 'slur'),

-- ========== 勧誘・広告 (ad) ==========
('出会い系', 'contains', 'log', 'ad'),
('副業で稼', 'contains', 'log', 'ad'),
('副業始めま', 'contains', 'log', 'ad'),
('簡単に稼げる', 'contains', 'log', 'ad'),
('不労所得', 'contains', 'log', 'ad'),
('LINE交換', 'contains', 'log', 'ad'),
('カカオ交換', 'contains', 'log', 'ad'),
('インスタ交換', 'contains', 'log', 'ad'),
('LINE追加', 'contains', 'log', 'ad'),
('友達追加して', 'contains', 'log', 'ad'),
('DMください', 'contains', 'log', 'ad'),
('連絡ください', 'contains', 'log', 'ad'),
('マルチ商法', 'contains', 'log', 'ad'),
('ネットワークビジネス', 'contains', 'log', 'ad'),
('MLM', 'contains', 'log', 'ad'),
('アムウェイ', 'contains', 'log', 'ad'),
('ニュースキン', 'contains', 'log', 'ad'),
('情報商材', 'contains', 'log', 'ad'),
('無料セミナー', 'contains', 'log', 'ad'),
('投資セミナー', 'contains', 'log', 'ad'),
('FX自動売買', 'contains', 'log', 'ad'),
('バイナリーオプション', 'contains', 'log', 'ad'),
('仮想通貨で稼', 'contains', 'log', 'ad'),
('限定募集', 'contains', 'log', 'ad'),
('先着順', 'contains', 'log', 'ad'),
('今だけ無料', 'contains', 'log', 'ad'),
('月利30', 'contains', 'log', 'ad'),
('利回り保証', 'contains', 'log', 'ad'),
('元本保証', 'contains', 'log', 'ad'),
('確実に儲かる', 'contains', 'log', 'ad'),
('楽して稼', 'contains', 'log', 'ad'),
('スマホだけで稼', 'contains', 'log', 'ad'),
('1日5分で', 'contains', 'log', 'ad'),
('誰でも簡単に', 'contains', 'log', 'ad'),
('自由な生活', 'contains', 'log', 'ad'),
('脱サラ', 'contains', 'log', 'ad'),
('権利収入', 'contains', 'log', 'ad'),
('配当金生活', 'contains', 'log', 'ad'),
('コンサル生募集', 'contains', 'log', 'ad'),
('生徒募集中', 'contains', 'log', 'ad'),
('オープンチャット招待', 'contains', 'log', 'ad'),
('グループ招待', 'contains', 'log', 'ad'),

-- ========== 勧誘・広告 regex ==========
('月収\d+万', 'regex', 'log', 'ad'),
('年収\d+万', 'regex', 'log', 'ad'),
('\d+万円稼', 'regex', 'log', 'ad'),
('(日給|時給)\d+万', 'regex', 'log', 'ad'),
('\d+万円(プレゼント|あげます)', 'regex', 'log', 'ad'),
('(固定ツイ|プロフ)(見て|から)', 'regex', 'log', 'ad'),

-- ========== 詐欺・フィッシング (spam) ==========
('振込先', 'contains', 'log', 'spam'),
('口座番号', 'contains', 'log', 'spam'),
('暗証番号', 'contains', 'log', 'spam'),
('パスワード教えて', 'contains', 'log', 'spam'),
('クレカ番号', 'contains', 'log', 'spam'),
('個人情報送って', 'contains', 'log', 'spam'),
('身分証送って', 'contains', 'log', 'spam'),
('マイナンバー', 'contains', 'log', 'spam'),
('闇バイト', 'contains', 'log', 'spam'),
('裏バイト', 'contains', 'log', 'spam'),
('高額バイト', 'contains', 'log', 'spam'),
('受け子', 'contains', 'log', 'spam'),
('出し子', 'contains', 'log', 'spam'),
('掛け子', 'contains', 'log', 'spam'),
('荷物受け取り', 'contains', 'log', 'spam'),
('口座貸し', 'contains', 'log', 'spam'),
('口座売', 'contains', 'log', 'spam'),
('名義貸し', 'contains', 'log', 'spam'),
('飛ばし携帯', 'contains', 'log', 'spam'),
('特殊詐欺', 'contains', 'log', 'spam'),
('オレオレ詐欺', 'contains', 'log', 'spam'),
('フィッシング', 'contains', 'log', 'spam'),
('架空請求', 'contains', 'log', 'spam'),
('当選しました', 'contains', 'log', 'spam'),
('懸賞当選', 'contains', 'log', 'spam'),
('アカウント売', 'contains', 'log', 'spam'),
('垢売り', 'contains', 'log', 'spam'),
('代行します', 'contains', 'log', 'spam'),
('レポート代行', 'contains', 'log', 'spam'),
('課題代行', 'contains', 'log', 'spam'),
('テスト代行', 'contains', 'log', 'spam'),
('単位売り', 'contains', 'log', 'spam'),
('卒論代行', 'contains', 'log', 'spam'),

-- ========== 詐欺・フィッシング regex ==========
('https?://.*(bit\.ly|t\.co|goo\.gl|tinyurl|is\.gd|rb\.gy)', 'regex', 'log', 'spam'),
('https?://[a-z0-9-]+\.(xyz|top|work|click|loan|racing)', 'regex', 'log', 'spam'),
('[0-9]{4}[-\s]?[0-9]{4}[-\s]?[0-9]{4}[-\s]?[0-9]{4}', 'regex', 'log', 'spam'),
('[0-9]{3}-?[0-9]{4}-?[0-9]{4}', 'regex', 'log', 'spam'),

-- ========== 暴力・犯罪 (other) ==========
('爆破予告', 'contains', 'log', 'other'),
('殺害予告', 'contains', 'log', 'other'),
('襲撃する', 'contains', 'log', 'other'),
('放火する', 'contains', 'log', 'other'),
('刺す', 'contains', 'log', 'other'),
('ナイフ持って', 'contains', 'log', 'other'),
('包丁持って', 'contains', 'log', 'other'),
('銃を持って', 'contains', 'log', 'other'),
('大麻', 'contains', 'log', 'other'),
('マリファナ', 'contains', 'log', 'other'),
('コカイン', 'contains', 'log', 'other'),
('覚醒剤', 'contains', 'log', 'other'),
('シャブ', 'contains', 'log', 'other'),
('MDMA', 'contains', 'log', 'other'),
('LSD', 'contains', 'log', 'other'),
('違法薬物', 'contains', 'log', 'other'),
('脱法ハーブ', 'contains', 'log', 'other'),
('脱法ドラッグ', 'contains', 'log', 'other'),
('売人', 'contains', 'log', 'other'),
('プッシャー', 'contains', 'log', 'other'),
('児童ポルノ', 'contains', 'log', 'other'),
('児ポ', 'contains', 'log', 'other'),
('ロリコン', 'contains', 'log', 'other'),
('ペドフィリア', 'contains', 'log', 'other'),
('盗撮', 'contains', 'log', 'other'),
('痴漢した', 'contains', 'log', 'other'),
('のぞき', 'contains', 'log', 'other'),
('ストーカー', 'contains', 'log', 'other'),
('つきまとい', 'contains', 'log', 'other'),
('リベンジポルノ', 'contains', 'log', 'other'),
('裸の写真', 'contains', 'log', 'other'),
('エロ動画', 'contains', 'log', 'other'),
('無修正', 'contains', 'log', 'other'),

-- ========== 下ネタ・性的 (sexual) ==========
('ちんこ', 'contains', 'log', 'sexual'),
('チンコ', 'contains', 'log', 'sexual'),
('ちんぽ', 'contains', 'log', 'sexual'),
('チンポ', 'contains', 'log', 'sexual'),
('まんこ', 'contains', 'log', 'sexual'),
('マンコ', 'contains', 'log', 'sexual'),
('おっぱい', 'contains', 'log', 'sexual'),
('オッパイ', 'contains', 'log', 'sexual'),
('巨乳', 'contains', 'log', 'sexual'),
('貧乳', 'contains', 'log', 'sexual'),
('爆乳', 'contains', 'log', 'sexual'),
('ケツ穴', 'contains', 'log', 'sexual'),
('アナル', 'contains', 'log', 'sexual'),
('フェラ', 'contains', 'log', 'sexual'),
('クンニ', 'contains', 'log', 'sexual'),
('パイズリ', 'contains', 'log', 'sexual'),
('手コキ', 'contains', 'log', 'sexual'),
('足コキ', 'contains', 'log', 'sexual'),
('素股', 'contains', 'log', 'sexual'),
('中出し', 'contains', 'log', 'sexual'),
('顔射', 'contains', 'log', 'sexual'),
('ぶっかけ', 'contains', 'log', 'sexual'),
('潮吹き', 'contains', 'log', 'sexual'),
('イキ顔', 'contains', 'log', 'sexual'),
('アヘ顔', 'contains', 'log', 'sexual'),
('勃起', 'contains', 'log', 'sexual'),
('射精', 'contains', 'log', 'sexual'),
('オナニー', 'contains', 'log', 'sexual'),
('自慰', 'contains', 'log', 'sexual'),
('シコシコ', 'contains', 'log', 'sexual'),
('シコった', 'contains', 'log', 'sexual'),
('抜いた', 'contains', 'log', 'sexual'),
('抜ける', 'contains', 'log', 'sexual'),
('おかず', 'contains', 'log', 'sexual'),
('ズリネタ', 'contains', 'log', 'sexual'),
('セックス', 'contains', 'log', 'sexual'),
('セフレ', 'contains', 'log', 'sexual'),
('ハメ撮り', 'contains', 'log', 'sexual'),
('乱交', 'contains', 'log', 'sexual'),
('3P', 'contains', 'log', 'sexual'),
('4P', 'contains', 'log', 'sexual'),
('NTR', 'contains', 'log', 'sexual'),
('寝取り', 'contains', 'log', 'sexual'),
('寝取られ', 'contains', 'log', 'sexual'),
('不倫', 'contains', 'log', 'sexual'),
('浮気相手', 'contains', 'log', 'sexual'),
('ワンナイト', 'contains', 'log', 'sexual'),
('やらせて', 'contains', 'log', 'sexual'),
('やらせろ', 'contains', 'log', 'sexual'),
('犯す', 'contains', 'log', 'sexual'),
('犯したい', 'contains', 'log', 'sexual'),
('レイプ', 'contains', 'log', 'sexual'),
('強姦', 'contains', 'log', 'sexual'),
('輪姦', 'contains', 'log', 'sexual'),
('痴漢', 'contains', 'log', 'sexual'),
('触りたい', 'contains', 'log', 'sexual'),
('舐めたい', 'contains', 'log', 'sexual'),
('挿入', 'contains', 'log', 'sexual'),
('ペニス', 'contains', 'log', 'sexual'),
('ヴァギナ', 'contains', 'log', 'sexual'),
('性器', 'contains', 'log', 'sexual'),
('陰茎', 'contains', 'log', 'sexual'),
('陰部', 'contains', 'log', 'sexual'),
('金玉', 'contains', 'log', 'sexual'),
('キンタマ', 'contains', 'log', 'sexual'),
('睾丸', 'contains', 'log', 'sexual'),
('クリトリス', 'contains', 'log', 'sexual'),
('前立腺', 'contains', 'log', 'sexual'),
('Gスポット', 'contains', 'log', 'sexual'),
('バイブ', 'contains', 'log', 'sexual'),
('ローター', 'contains', 'log', 'sexual'),
('オナホ', 'contains', 'log', 'sexual'),
('ディルド', 'contains', 'log', 'sexual'),
('大人のおもちゃ', 'contains', 'log', 'sexual'),
('コンドーム', 'contains', 'log', 'sexual'),
('ゴムなし', 'contains', 'log', 'sexual'),
('生挿入', 'contains', 'log', 'sexual'),
('生セックス', 'contains', 'log', 'sexual'),
('エロい体', 'contains', 'log', 'sexual'),
('いやらしい体', 'contains', 'log', 'sexual'),
('脱いで', 'contains', 'log', 'sexual'),
('裸になって', 'contains', 'log', 'sexual'),
('裸見せて', 'contains', 'log', 'sexual'),
('胸見せて', 'contains', 'log', 'sexual'),
('パンツ見せて', 'contains', 'log', 'sexual'),
('下着見せて', 'contains', 'log', 'sexual'),
('スカートの中', 'contains', 'log', 'sexual'),
('パンチラ', 'contains', 'log', 'sexual'),
('胸チラ', 'contains', 'log', 'sexual'),
('ノーブラ', 'contains', 'log', 'sexual'),
('ノーパン', 'contains', 'log', 'sexual'),
('透けブラ', 'contains', 'log', 'sexual'),
('ブルマ', 'contains', 'log', 'sexual'),
('スク水', 'contains', 'log', 'sexual'),
('制服プレイ', 'contains', 'log', 'sexual'),
('コスプレえっち', 'contains', 'log', 'sexual'),
('SM', 'contains', 'log', 'sexual'),
('緊縛', 'contains', 'log', 'sexual'),
('調教', 'contains', 'log', 'sexual'),
('奴隷', 'contains', 'log', 'sexual'),
('ご主人様', 'contains', 'log', 'sexual'),
('メス豚', 'contains', 'log', 'sexual'),
('雌犬', 'contains', 'log', 'sexual'),
('変態', 'contains', 'log', 'sexual'),
('ド変態', 'contains', 'log', 'sexual'),
('ドM', 'contains', 'log', 'sexual'),
('ドS', 'contains', 'log', 'sexual'),
('痴女', 'contains', 'log', 'sexual'),
('淫乱', 'contains', 'log', 'sexual'),
('ビッチ', 'contains', 'log', 'sexual'),
('淫売', 'contains', 'log', 'sexual'),
('娼婦', 'contains', 'log', 'sexual'),
('風俗', 'contains', 'log', 'sexual'),
('ソープ', 'contains', 'log', 'sexual'),
('デリヘル', 'contains', 'log', 'sexual'),
('ピンサロ', 'contains', 'log', 'sexual'),
('ヘルス', 'contains', 'log', 'sexual'),
('キャバ嬢', 'contains', 'log', 'sexual'),
('ホスト狂い', 'contains', 'log', 'sexual'),
('円光', 'contains', 'log', 'sexual'),
('神待ち', 'contains', 'log', 'sexual'),
('割り切り', 'contains', 'log', 'sexual'),
('ホテル行こ', 'contains', 'log', 'sexual'),
('ラブホ', 'contains', 'log', 'sexual'),
('AV女優', 'contains', 'log', 'sexual'),
('AV男優', 'contains', 'log', 'sexual'),
('エロ同人', 'contains', 'log', 'sexual'),
('エロ漫画', 'contains', 'log', 'sexual'),
('エロゲ', 'contains', 'log', 'sexual'),
('薄い本', 'contains', 'log', 'sexual'),
('R18', 'contains', 'log', 'sexual'),
('NSFW', 'contains', 'log', 'sexual'),
('Xvideos', 'contains', 'log', 'sexual'),
('Pornhub', 'contains', 'log', 'sexual'),
('FANZAで', 'contains', 'log', 'sexual'),
('DMM動画', 'contains', 'log', 'sexual'),

-- ========== 下ネタ regex ==========
('(おっぱ|オッパ)い+', 'regex', 'log', 'sexual'),
('(ち|チ)(ん|ン)(こ|コ|ぽ|ポ)', 'regex', 'log', 'sexual'),
('(ま|マ)(ん|ン)(こ|コ)', 'regex', 'log', 'sexual'),
('(えっち|エッチ)(し|しよ|しない)', 'regex', 'log', 'sexual'),
('(やり|ヤリ)(たい|たくない？|目的)', 'regex', 'log', 'sexual'),
('(裸|ヌード)(画像|写真|動画)', 'regex', 'log', 'sexual'),
('(胸|おっぱい|体)(触|揉)', 'regex', 'log', 'sexual'),
('(何カップ|スリーサイズ)', 'regex', 'log', 'sexual'),

-- ========== 軽度・様子見 (general) ==========
('バカ', 'contains', 'log', 'general'),
('ばか', 'contains', 'log', 'general'),
('アホ', 'contains', 'log', 'general'),
('あほ', 'contains', 'log', 'general'),
('マジうぜえ', 'contains', 'log', 'general'),
('だるい', 'contains', 'log', 'general'),
('ダルい', 'contains', 'log', 'general'),
('つまらん', 'contains', 'log', 'general'),
('無能', 'contains', 'log', 'general'),
('雑魚', 'contains', 'log', 'general'),
('ザコ', 'contains', 'log', 'general'),
('にわか', 'contains', 'log', 'general'),
('ニワカ', 'contains', 'log', 'general'),
('陰キャ', 'contains', 'log', 'general'),
('陽キャ', 'contains', 'log', 'general'),
('チー牛', 'contains', 'log', 'general'),
('弱者男性', 'contains', 'log', 'general'),
('弱男', 'contains', 'log', 'general'),
('こどおじ', 'contains', 'log', 'general'),
('こどおば', 'contains', 'log', 'general'),
('老害', 'contains', 'log', 'general'),
('ゆとり', 'contains', 'log', 'general'),
('さとり世代', 'contains', 'log', 'general'),
('意識高い系', 'contains', 'log', 'general'),
('黙れ', 'contains', 'log', 'general'),
('だまれ', 'contains', 'log', 'general'),
('うるさい', 'contains', 'log', 'general'),
('関わるな', 'contains', 'log', 'general'),
('話しかけるな', 'contains', 'log', 'general'),
('近寄るな', 'contains', 'log', 'general')

ON CONFLICT DO NOTHING;
